remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-seo-tag

header_pages:
  - index.md
  - about.md

title: Derps-Page
style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

footer: '<a href="https://chat.openai.com/">thanks to ChatGPT</a>'

google_analytics: UA-NNNNNNNN-N
